### PR TITLE
152 normalize weights update

### PR DESCRIPTION
**Pull request by MikeJSeo**

### CODE REVIEW

**Review by gravesti — CHANGES_REQUESTED** [review]
Looks great. Can you add a test?

**Comment by MikeJSeo** [comment]
Test on what? @gravesti :)

**Comment by gravesti** [comment]
That the function produces the right plot if you have normalize weight = TRUE or FALSE

**Comment by MikeJSeo** [comment]
Checks passed :)

**Review by gravesti — APPROVED** [review]
Thanks @MikeJSeo !

**Pull request merged**
