### PR TITLE
83 update bucher function

### PR DESCRIPTION
**Pull request by MikeJSeo**

### CODE REVIEW

**Comment by MikeJSeo** [comment]
I don't get this R CMD error..
I modified the print method too..

**Comment by MikeJSeo** [comment]
Sure, just merge it in if name change is the only issue

**Review by gravesti — CHANGES_REQUESTED** [review]
@MikeJSeo Looks good! Can you check why the test is failing? I've added a few suggestions as well.

**Comment by MikeJSeo** [comment]
How come when I run this code:
  result <- bucher(
    trt = list(est = log(1.1), se = 0.2),
    com = list(est = log(1.3), se = 0.18),
    conf_lv = 0.9
  )
result

it doesn't give print anything
but I have to specifically write

print(result)

**Review by gravesti — COMMENTED** [review]
@MikeJSeo Could you also add tests for print and find_SE_from_CI?

**Comment by MikeJSeo** [comment]
@gravesti I think it all passed!

**Review by gravesti — APPROVED** [review]
Thanks @MikeJSeo !

**Pull request merged**
