### PR TITLE
16 add nice survey about ess

### PR DESCRIPTION
**Pull request by miranta-antoniou-roche**

### CODE REVIEW

**Comment by MikeJSeo** [comment]
Hi Miranta, 
If you just add text like that the text doesn't fully show.. 
image

Also another problem is this breaks when we do par(mfrow = c(1, 2))
I wrote a ggplot function for weights.. can we maybe look at that later?

**Comment by miranta-antoniou-roche** [comment]
Hi Mike, thank you for looking at it. That is weird; I was able to see the full text in my screen. Yes, let's check it later. I found mtext() as a simple solution and I gave it a try :).

**Comment by MikeJSeo** [comment]
Yea let's ask Greg/Issac about this :) I'm not too sure..

**Comment by gravesti** [comment]
This is covered in #35

**Pull request closed without merging**
